env:
  browser: true
  es2021: true
  node: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - '@typescript-eslint'
rules:
  indent:
    - error
    - tab
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - double
  semi:
    - error
    - always  
  comma-dangle:
    - error
    - always-multiline
  "@typescript-eslint/semi": 
    - error
  "@typescript-eslint/member-delimiter-style":
    - error
    - multiline:
          delimiter: "semi"
          requireLast: true
      singleline:
          delimiter: "semi"
          requireLast: true
  key-spacing:
    - error
    - mode: strict
  "@typescript-eslint/type-annotation-spacing":
    - error
    - before: true
      after: true
  no-extra-parens:
    - error
    - all